In [3]:
import torch
import numpy as np

In [4]:
data = [[1, 2], [3, 4]]
data_tensor = torch.tensor(data)
print(data_tensor, type(data_tensor))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [13]:
data = [[1, 2], [3, 4], [5, 6]]
np_data = np.array(data)
print(np_data, type(np_data))
np_data_tensor = torch.from_numpy(np_data)
print(np_data_tensor, type(np_data_tensor), np_data_tensor.shape)

[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4],
        [5, 6]]) <class 'torch.Tensor'> torch.Size([3, 2])


In [6]:
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

In [7]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
torch.rand(2, 5)

tensor([[0.1415, 0.3732, 0.5174, 0.1156, 0.7069],
        [0.6161, 0.4621, 0.9341, 0.3098, 0.5485]])

In [18]:
torch.rand(1, 2, 5)

tensor([[[0.7923, 0.9017, 0.7377, 0.5393, 0.8338],
         [0.0090, 0.7592, 0.3297, 0.3421, 0.6486]]])

In [20]:
x = torch.rand(2, 5)
torch.ones_like(x)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [21]:
print(x)

tensor([[0.0425, 0.2126, 0.3593, 0.6357, 0.2607],
        [0.6686, 0.5303, 0.4162, 0.0816, 0.6608]])


In [22]:
# copy
y = x.detach()
print(y)

tensor([[0.0425, 0.2126, 0.3593, 0.6357, 0.2607],
        [0.6686, 0.5303, 0.4162, 0.0816, 0.6608]])


In [32]:
# index 0 row
x[0, :] + 3

tensor([3.0425, 3.2126, 3.3593, 3.6357, 3.2607])

In [30]:
# index 4 column
x[:, 4] + 1

tensor([1.2607, 1.6608])

In [34]:
rand1 = torch.rand(2)
rand2 = torch.rand(2)
print(rand1, rand2)
torch.matmul(rand1, rand2)

tensor([0.6648, 0.0182]) tensor([0.4775, 0.7089])


tensor(0.3304)

In [38]:
rand1 = torch.rand(2, 5)
rand2 = torch.rand(5, 2)
print(rand1, rand2)
torch.matmul(rand1, rand2)

tensor([[0.4182, 0.2736, 0.1304, 0.8511, 0.1565],
        [0.5344, 0.9403, 0.2007, 0.7003, 0.4790]]) tensor([[0.2888, 0.6237],
        [0.6239, 0.4405],
        [0.3864, 0.2419],
        [0.5964, 0.8910],
        [0.8762, 0.8779]])


tensor([[0.9866, 1.3086],
        [1.6559, 1.8405]])