In [2]:
import numpy as np


def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))
 

x = np.array([0.5, 0.1, -0.2])
target = 0.6
learnrate = 0.5 
 
weights_input_hidden = np.array([[0.5, -0.6],
                                 [0.1, -0.2],
                                 [0.1, 0.7]])

weights_hidden_output = np.array([0.1, -0.3])

## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)
print(hidden_layer_input, hidden_layer_output)
 
output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)
print(output_layer_in, output) 

[ 0.24 -0.46] [0.55971365 0.38698582]
-0.06012438223148006 0.48497343084992534


In [16]:
error = target - output
output_error_term = error * output * (1 - output)
hidden_error_term = np.dot(output_error_term, weights_hidden_output) * hidden_layer_output * (1 - hidden_layer_output)
print(error, output_error_term, hidden_error_term)

0.11502656915007464 0.028730669543515018 [ 0.00070802 -0.00204471]


In [17]:
learnrate * output_error_term * hidden_layer_output

array([0.00804047, 0.00555918])

In [18]:
learnrate * hidden_error_term * x[:, None]

array([[ 1.77005547e-04, -5.11178506e-04],
       [ 3.54011093e-05, -1.02235701e-04],
       [-7.08022187e-05,  2.04471402e-04]])

In [19]:
x[:, None]

array([[ 0.5],
       [ 0.1],
       [-0.2]])