In [4]:
import torch
import numpy as np

In [ ]:
features_raw = [[1,2], [3,4]]

In [ ]:
features = torch.tensor(features_raw)

In [ ]:
features

tensor([[1, 2],
        [3, 4]])

In [ ]:
features.shape

torch.Size([2, 2])

In [ ]:
n_records, n_inputs = features.shape

In [ ]:
n_hidden = 2

In [ ]:
weights_input_to_hidden = np.random.normal(0, n_inputs**-0.5, size=(n_inputs, n_hidden))

In [ ]:
weights_input_to_hidden

array([[-0.1605675 , -0.1682594 ],
       [ 0.72074157,  0.97743627]])

In [ ]:
hidden_inputs = np.dot(weights_input_to_hidden, features)

In [ ]:
hidden_inputs

array([[-0.66534571, -0.9941726 ],
       [ 3.65305038,  5.35122823]])

In [ ]:
np.dot([1,2], [[4, 5, 6], [4, 5, 6]])

array([12, 15, 18])

In [ ]:
np.dot([[4, 5, 6], [4, 5, 6]], [1, 2, 3])

array([32, 32])

In [ ]:
features = np.array([ 0.49671415, -0.1382643 ,  0.64768854])
print(features)
print(features.T)
features[:, None]

[ 0.49671415 -0.1382643   0.64768854]
[ 0.49671415 -0.1382643   0.64768854]


array([[ 0.49671415],
       [-0.1382643 ],
       [ 0.64768854]])

In [ ]:
print(np.array(features, ndmin=2))
np.array(features, ndmin=2).T

[[ 0.49671415 -0.1382643   0.64768854]]


array([[ 0.49671415],
       [-0.1382643 ],
       [ 0.64768854]])

In [ ]:
np.random.seed(42)

In [ ]:
np.random.randn(4)

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986])

In [ ]:
# Network size
N_input = 4
N_hidden = 3
N_output = 2

np.random.seed(42)
# Make some fake data
X = np.random.randn(4)

weights_input_to_hidden = np.random.normal(0, scale=0.1, size=(N_input, N_hidden))
weights_hidden_to_output = np.random.normal(0, scale=0.1, size=(N_hidden, N_output))

In [ ]:
weights_input_to_hidden

array([[-0.02341534, -0.0234137 ,  0.15792128],
       [ 0.07674347, -0.04694744,  0.054256  ],
       [-0.04634177, -0.04657298,  0.02419623],
       [-0.19132802, -0.17249178, -0.05622875]])

In [ ]:
weights_hidden_to_output

array([[-0.10128311,  0.03142473],
       [-0.09080241, -0.14123037],
       [ 0.14656488, -0.02257763]])

In [ ]:
X

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986])

In [ ]:
np.dot([1,2, 3, 4], [
                [1, 3,1], 
                [2, 3, 1],
    [1,3, 1],
    [1,3, 1]
              ])

array([12, 30, 10])

In [ ]:
np.dot(X, weights_input_to_hidden)

array([-0.34365494, -0.29801368,  0.00097362])

In [ ]:
def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

In [ ]:
sigmoid(np.dot(X, weights_input_to_hidden))

array([0.41492192, 0.42604313, 0.5002434 ])

In [ ]:
np.dot([1,2,4], [[1,2],[1,2],[1,2]])

array([ 7, 14])

In [5]:
def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

In [6]:
sigmoid(2.4)

0.9168273035060777

In [7]:
sigmoid(2)

0.8807970779778823

In [8]:
sigmoid(1.4)

0.8021838885585817