In [1]:
import numpy as np

In [2]:
x = np.array([1, -2, 3, -4])

In [3]:
np.absolute(x)

array([1, 2, 3, 4])

In [4]:
np.sum(x)

-2

In [5]:
np.sum(np.absolute(x))

10

In [6]:
np.square(x)

array([ 1,  4,  9, 16])

In [7]:
x

array([ 1, -2,  3, -4])

In [8]:
x.T

array([ 1, -2,  3, -4])

In [9]:
np.dot(x, x)

30

In [10]:
np.dot(x, x.T)

30

In [11]:
np.sum(np.square(x))

30

In [14]:
import torch
from torch import nn

In [39]:
input = torch.randn(3, 2)
input

tensor([[-0.2243, -0.5358],
        [ 2.4565, -0.8889],
        [ 0.6350,  1.0165]])

In [40]:
print(input.shape)
m = nn.Linear(2, 2)

torch.Size([3, 2])


In [41]:
output = m(input)
output

tensor([[ 0.1813,  0.9289],
        [ 0.4088,  0.6526],
        [ 0.7442, -0.1632]], grad_fn=<AddmmBackward0>)

In [42]:
m.weight

Parameter containing:
tensor([[ 0.1236,  0.2942],
        [-0.1824, -0.6026]], requires_grad=True)

In [43]:
m.bias

Parameter containing:
tensor([0.3667, 0.5651], requires_grad=True)

In [53]:
m_b = nn.Linear(2, 2, bias=False)
output_b = m_b(input)
output_b

tensor([[ 0.3841, -0.2514],
        [ 0.3810,  0.7560],
        [-0.7477,  0.5639]], grad_fn=<MmBackward0>)

In [54]:
m_b.weight

Parameter containing:
tensor([[-0.0906, -0.6790],
        [ 0.4148,  0.2957]], requires_grad=True)

In [55]:
m_b.bias

In [56]:
input.matmul(m_b.weight.t())

tensor([[ 0.3841, -0.2514],
        [ 0.3810,  0.7560],
        [-0.7477,  0.5639]], grad_fn=<MmBackward0>)

In [57]:
input

tensor([[-0.2243, -0.5358],
        [ 2.4565, -0.8889],
        [ 0.6350,  1.0165]])

In [66]:
print((-0.2243 * -0.0906) + (-0.5358 * -0.6790))
print((-0.2243 * 0.4148) + (-0.5358 * 0.2957))

0.3841297800000001
-0.2514757


In [63]:
p = torch.tensor([[1, 2], [1, 2], [1, 2]])
q = torch.tensor([[5, 5], [3, 3]])
p.matmul(q.t())

tensor([[15,  9],
        [15,  9],
        [15,  9]])

In [64]:
print(q)
print(q.t())

tensor([[5, 5],
        [3, 3]])
tensor([[5, 3],
        [5, 3]])


In [75]:
j = nn.Parameter(torch.ones_like(m_b.weight))
j

Parameter containing:
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [85]:
k = torch.tensor([1, 2, 3])
l = [p.sum() for p in k]
print(l)

[tensor(1), tensor(2), tensor(3)]
