In [2]:
import torch

In [3]:
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [4]:
torch.rand(3, 4, 1, 2)

tensor([[[[0.3174, 0.7966]],

         [[0.4164, 0.0921]],

         [[0.6687, 0.7334]],

         [[0.8210, 0.8660]]],


        [[[0.7449, 0.5753]],

         [[0.7955, 0.8204]],

         [[0.8142, 0.7669]],

         [[0.3254, 0.6043]]],


        [[[0.7238, 0.2828]],

         [[0.0938, 0.1449]],

         [[0.2176, 0.1909]],

         [[0.7455, 0.1081]]]])

In [23]:
torch.triu(torch.ones(4, 4, dtype=torch.float16) * .5)

tensor([[0.5000, 0.5000, 0.5000, 0.5000],
        [0.0000, 0.5000, 0.5000, 0.5000],
        [0.0000, 0.0000, 0.5000, 0.5000],
        [0.0000, 0.0000, 0.0000, 0.5000]], dtype=torch.float16)

In [9]:
torch.ones(4, 4) * 0.5

tensor([[0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000]])

In [19]:
x.dtype

torch.float16

In [24]:
classes = ('plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck')
type(classes)

tuple

In [25]:
classes[2]

'bird'

In [2]:
import numpy as np

In [3]:
n_features = 4
np.random.normal(scale=1/n_features**.5, size=n_features)

array([-0.08305928, -0.62077691, -0.40224807,  0.61294595])

In [4]:
w = np.random.normal(scale=1/n_features**.5, size=n_features)
i = np.random.normal(scale=1/n_features**.5, size=n_features)
print(w)
print(i)
x = np.dot(w, i)
print(x)

[-1.07134073  0.48194186  0.18266239  0.38304843]
[0.72567813 0.14446887 0.06506024 0.31680163]
-0.5745885159065658
